[package]
name = "functional-counter"
version = "0.1.0"
authors = ["Hamza <muhammadhamza1311@gmail.com>"]
edition = "2018"

[dependencies]
yew = { path =  "../../yew" }
yew-functional = { path =  "../../yew-functional" }
js-sys = "0.3"
